language: cpp

compiler:
  - gcc

dist: trusty
sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-6
      - libstdc++6
      - libboost-dev
      - ninja-build
env: COMPILER=g++-6

install:
  - |
    pushd /tmp
    travis_retry wget --quiet --no-check-certificate https://cmake.org/files/v3.8/cmake-3.8.0-rc2-Linux-x86_64.tar.gz
    tar -xf cmake-3.8.0-rc2-Linux-x86_64.tar.gz
    popd

script:
  - |
    export PATH=/tmp/cmake-3.8.0-rc2-Linux-x86_64/bin:${PATH}
    cmake --version
    python ci.py ubuntu build-all
