language: cpp

clang: &clang
  os: linux
  dist: xenial
  python: "3.7"
  compiler: clang
  addons:
    apt:
      sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-trusty-8
      packages:
        - clang-8
        - libstdc++-8-dev
        - python3-pip

matrix:
  include:
    - name: "Clang 8.0 Release"
      <<: *clang
      env:
        - PROFILE=clang-8-r-static
    - name: "Clang 8.0 Debug"
      <<: *clang
      env:
        - PROFILE=clang-8-d-shared

install:
  - ./ci/travis/install.sh

script:
  - ./ci/travis/run.sh
