platform:
  - Win32

os: Visual Studio 2015

environment:
  BOOST_ROOT: C:\Libraries\boost_1_62_0
  PYTHON: "C:\\Python35"

build_script:
  - cmd: >-
      SET PATH=%PATH%;%PYTHON%\Scripts\

      python lp3-core-ci.py windows
